apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -v -f /home/michael/Desktop/kompose/docker-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath -v -f /home/michael/Desktop/kompose/docker-compose.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network: "true"
        io.kompose.service: mongodb
    spec:
      containers:
        - image: mongo:3.6
          name: gio-apim-mongodb
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: data-mongo
            - mountPath: /var/log/mongodb
              name: mongodb-hostpath1
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /opt/gravitee/mongo
          name: data-mongo
        - hostPath:
            path: /opt/gravitee/logs/apim-mongodb
          name: mongodb-hostpath1
status: {}
